//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotoGestionClientes.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Textos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Textos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RotoGestionClientes.Resources.Textos", typeof(Textos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar datos Roto.
        /// </summary>
        internal static string Actualizar_datos_Roto {
            get {
                return ResourceManager.GetString("Actualizar_datos_Roto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aguja.
        /// </summary>
        internal static string Aguja {
            get {
                return ResourceManager.GetString("Aguja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alias.
        /// </summary>
        internal static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El fichero no es válido..
        /// </summary>
        internal static string ArchivoNoValido {
            get {
                return ResourceManager.GetString("ArchivoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atrás.
        /// </summary>
        internal static string Atras {
            get {
                return ResourceManager.GetString("Atras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balconeras.
        /// </summary>
        internal static string Balconeras {
            get {
                return ResourceManager.GetString("Balconeras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banco de marcos.
        /// </summary>
        internal static string BancoMarcos {
            get {
                return ResourceManager.GetString("BancoMarcos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bisagras.
        /// </summary>
        internal static string Bisagras {
            get {
                return ResourceManager.GetString("Bisagras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bisagras en soldadora.
        /// </summary>
        internal static string BisagrasSoldadora {
            get {
                return ResourceManager.GetString("BisagrasSoldadora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bombillo.
        /// </summary>
        internal static string Bombillo {
            get {
                return ResourceManager.GetString("Bombillo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centro de mecanizado.
        /// </summary>
        internal static string CentroMecanizado {
            get {
                return ResourceManager.GetString("CentroMecanizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerraduras.
        /// </summary>
        internal static string Cerraduras {
            get {
                return ResourceManager.GetString("Cerraduras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cilindros.
        /// </summary>
        internal static string Cilindros {
            get {
                return ResourceManager.GetString("Cilindros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un cliente con ese nombre o variantes. Se importará como: .
        /// </summary>
        internal static string ClienteExistente {
            get {
                return ResourceManager.GetString("ClienteExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente exportado correctamente..
        /// </summary>
        internal static string ClienteExportado {
            get {
                return ResourceManager.GetString("ClienteExportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente importado correctamente..
        /// </summary>
        internal static string ClienteImportado {
            get {
                return ResourceManager.GetString("ClienteImportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado el cliente..
        /// </summary>
        internal static string ClienteNoEncontrado {
            get {
                return ResourceManager.GetString("ClienteNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        internal static string Clientes {
            get {
                return ResourceManager.GetString("Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a clientes.
        /// </summary>
        internal static string ClientesMinuscula {
            get {
                return ResourceManager.GetString("ClientesMinuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios.
        /// </summary>
        internal static string Comentarios {
            get {
                return ResourceManager.GetString("Comentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completa los datos para crear el cliente.
        /// </summary>
        internal static string CompletaDatosCliente {
            get {
                return ResourceManager.GetString("CompletaDatosCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea eliminar el cliente .
        /// </summary>
        internal static string ConfirmarEliminarCliente {
            get {
                return ResourceManager.GetString("ConfirmarEliminarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consumen.
        /// </summary>
        internal static string Consumen {
            get {
                return ResourceManager.GetString("Consumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correderas.
        /// </summary>
        internal static string Correderas {
            get {
                return ResourceManager.GetString("Correderas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear actualización de datos.
        /// </summary>
        internal static string Crear_actualizacion_Roto {
            get {
                return ResourceManager.GetString("Crear_actualizacion_Roto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear fichero configurador.
        /// </summary>
        internal static string CrearConfig {
            get {
                return ResourceManager.GetString("CrearConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos corruptos. Cierre y reabra la aplicación.
        /// </summary>
        internal static string DatosCorruptos {
            get {
                return ResourceManager.GetString("DatosCorruptos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos generales.
        /// </summary>
        internal static string DatosGenerales {
            get {
                return ResourceManager.GetString("DatosGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Definir agujas por perfil.
        /// </summary>
        internal static string DeinifirAgujasPerfil {
            get {
                return ResourceManager.GetString("DeinifirAgujasPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DLO.
        /// </summary>
        internal static string Dlo {
            get {
                return ResourceManager.GetString("Dlo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento.
        /// </summary>
        internal static string Documento {
            get {
                return ResourceManager.GetString("Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes seleccionar un documento..
        /// </summary>
        internal static string DocumentoObligatorio {
            get {
                return ResourceManager.GetString("DocumentoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentos.
        /// </summary>
        internal static string Documentos {
            get {
                return ResourceManager.GetString("Documentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editando cliente.
        /// </summary>
        internal static string EditandoCliente {
            get {
                return ResourceManager.GetString("EditandoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elevables.
        /// </summary>
        internal static string Elevables {
            get {
                return ResourceManager.GetString("Elevables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elevables/Plegables.
        /// </summary>
        internal static string ElevablesPlegables {
            get {
                return ResourceManager.GetString("ElevablesPlegables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se eliminará al cliente y todos los datos relacionado con él..
        /// </summary>
        internal static string EliminarCliente {
            get {
                return ResourceManager.GetString("EliminarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al exportar.
        /// </summary>
        internal static string ErrorAlExportar {
            get {
                return ResourceManager.GetString("ErrorAlExportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al importar cliente:.
        /// </summary>
        internal static string ErrorAlImportar {
            get {
                return ResourceManager.GetString("ErrorAlImportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estándar.
        /// </summary>
        internal static string Estandar {
            get {
                return ResourceManager.GetString("Estandar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar.
        /// </summary>
        internal static string Exportar {
            get {
                return ResourceManager.GetString("Exportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar clientes.
        /// </summary>
        internal static string ExportarClientes {
            get {
                return ResourceManager.GetString("ExportarClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exterior.
        /// </summary>
        internal static string Exterior {
            get {
                return ResourceManager.GetString("Exterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fichero.
        /// </summary>
        internal static string Fichero {
            get {
                return ResourceManager.GetString("Fichero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar.
        /// </summary>
        internal static string Finalizar {
            get {
                return ResourceManager.GetString("Finalizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hoja pasiva.
        /// </summary>
        internal static string HojaPasiva {
            get {
                return ResourceManager.GetString("HojaPasiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar cliente.
        /// </summary>
        internal static string ImportarCliente {
            get {
                return ResourceManager.GetString("ImportarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes indicar un nombre para el documento..
        /// </summary>
        internal static string IndicarNombreDoc {
            get {
                return ResourceManager.GetString("IndicarNombreDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informes.
        /// </summary>
        internal static string Informes {
            get {
                return ResourceManager.GetString("Informes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inline.
        /// </summary>
        internal static string Inline {
            get {
                return ResourceManager.GetString("Inline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interior.
        /// </summary>
        internal static string Interior {
            get {
                return ResourceManager.GetString("Interior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manillas.
        /// </summary>
        internal static string Manillas {
            get {
                return ResourceManager.GetString("Manillas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimiento.
        /// </summary>
        internal static string Mantenimiento {
            get {
                return ResourceManager.GetString("Mantenimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Máquinas.
        /// </summary>
        internal static string Maquinas {
            get {
                return ResourceManager.GetString("Maquinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca.
        /// </summary>
        internal static string Marca {
            get {
                return ResourceManager.GetString("Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú principal.
        /// </summary>
        internal static string Menu_principal {
            get {
                return ResourceManager.GetString("Menu_principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ningún fichero seleccionado.
        /// </summary>
        internal static string NingunFichero {
            get {
                return ResourceManager.GetString("NingunFichero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre documento.
        /// </summary>
        internal static string NombreDocumento {
            get {
                return ResourceManager.GetString("NombreDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nomenclatura.
        /// </summary>
        internal static string Nomenclatura {
            get {
                return ResourceManager.GetString("Nomenclatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo cliente.
        /// </summary>
        internal static string NuevoCliente {
            get {
                return ResourceManager.GetString("NuevoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oscilobatientes.
        /// </summary>
        internal static string Oscilobatientes {
            get {
                return ResourceManager.GetString("Oscilobatientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        internal static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plantilla.
        /// </summary>
        internal static string Plantilla {
            get {
                return ResourceManager.GetString("Plantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plegables.
        /// </summary>
        internal static string Plegables {
            get {
                return ResourceManager.GetString("Plegables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por perfil.
        /// </summary>
        internal static string PorPerfil {
            get {
                return ResourceManager.GetString("PorPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Practicables.
        /// </summary>
        internal static string Practicables {
            get {
                return ResourceManager.GetString("Practicables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puertas.
        /// </summary>
        internal static string Puertas {
            get {
                return ResourceManager.GetString("Puertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puerta secundaria.
        /// </summary>
        internal static string PuertaSecundaria {
            get {
                return ResourceManager.GetString("PuertaSecundaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable.
        /// </summary>
        internal static string Responsable {
            get {
                return ResourceManager.GetString("Responsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string Salir {
            get {
                return ResourceManager.GetString("Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SapId.
        /// </summary>
        internal static string SapId {
            get {
                return ResourceManager.GetString("SapId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguridad.
        /// </summary>
        internal static string Seguridad {
            get {
                return ResourceManager.GetString("Seguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se han exportado .
        /// </summary>
        internal static string SeHanExportado {
            get {
                return ResourceManager.GetString("SeHanExportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionados.
        /// </summary>
        internal static string Seleccionados {
            get {
                return ResourceManager.GetString("Seleccionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar cilindros.
        /// </summary>
        internal static string SeleccionarCilindros {
            get {
                return ResourceManager.GetString("SeleccionarCilindros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar clientes para exportar.
        /// </summary>
        internal static string SeleccionarClientes {
            get {
                return ResourceManager.GetString("SeleccionarClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar documento.
        /// </summary>
        internal static string SeleccionarDocumento {
            get {
                return ResourceManager.GetString("SeleccionarDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar todos.
        /// </summary>
        internal static string SeleccionarTodos {
            get {
                return ResourceManager.GetString("SeleccionarTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione al menos un cliente..
        /// </summary>
        internal static string SeleccioneUnCliente {
            get {
                return ResourceManager.GetString("SeleccioneUnCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sí.
        /// </summary>
        internal static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        internal static string Siguiente {
            get {
                return ResourceManager.GetString("Siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Software.
        /// </summary>
        internal static string Software {
            get {
                return ResourceManager.GetString("Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soporte compás.
        /// </summary>
        internal static string SoporteCompas {
            get {
                return ResourceManager.GetString("SoporteCompas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soporte de marco.
        /// </summary>
        internal static string SoporteMarco {
            get {
                return ResourceManager.GetString("SoporteMarco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        internal static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de perfil.
        /// </summary>
        internal static string TipoPerfil {
            get {
                return ResourceManager.GetString("TipoPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos.
        /// </summary>
        internal static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total: .
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triple taladro en centro de mecanizado.
        /// </summary>
        internal static string TripleTaladroCentro {
            get {
                return ResourceManager.GetString("TripleTaladroCentro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validación.
        /// </summary>
        internal static string Validación {
            get {
                return ResourceManager.GetString("Validación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventanas.
        /// </summary>
        internal static string Ventanas {
            get {
                return ResourceManager.GetString("Ventanas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver resumen.
        /// </summary>
        internal static string VerResumen {
            get {
                return ResourceManager.GetString("VerResumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión de los datos:.
        /// </summary>
        internal static string Version_datos {
            get {
                return ResourceManager.GetString("Version_datos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver al menú principal.
        /// </summary>
        internal static string VolverMenu {
            get {
                return ResourceManager.GetString("VolverMenu", resourceCulture);
            }
        }
    }
}
