//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotoGestionClientes.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Textos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Textos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RotoGestionClientes.Resources.Textos", typeof(Textos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar datos Roto.
        /// </summary>
        internal static string Actualizar_datos_Roto {
            get {
                return ResourceManager.GetString("Actualizar_datos_Roto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El fichero no es válido..
        /// </summary>
        internal static string ArchivoNoValido {
            get {
                return ResourceManager.GetString("ArchivoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un cliente con ese nombre o variantes. Se importará como: .
        /// </summary>
        internal static string ClienteExistente {
            get {
                return ResourceManager.GetString("ClienteExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente exportado correctamente..
        /// </summary>
        internal static string ClienteExportado {
            get {
                return ResourceManager.GetString("ClienteExportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente importado correctamente..
        /// </summary>
        internal static string ClienteImportado {
            get {
                return ResourceManager.GetString("ClienteImportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado el cliente..
        /// </summary>
        internal static string ClienteNoEncontrado {
            get {
                return ResourceManager.GetString("ClienteNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        internal static string Clientes {
            get {
                return ResourceManager.GetString("Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a clientes.
        /// </summary>
        internal static string ClientesMinuscula {
            get {
                return ResourceManager.GetString("ClientesMinuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios.
        /// </summary>
        internal static string Comentarios {
            get {
                return ResourceManager.GetString("Comentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea eliminar el cliente .
        /// </summary>
        internal static string ConfirmarEliminarCliente {
            get {
                return ResourceManager.GetString("ConfirmarEliminarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear actualización de datos.
        /// </summary>
        internal static string Crear_actualizacion_Roto {
            get {
                return ResourceManager.GetString("Crear_actualizacion_Roto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear fichero configurador.
        /// </summary>
        internal static string CrearConfig {
            get {
                return ResourceManager.GetString("CrearConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se eliminará al cliente y todos los datos relacionado con él..
        /// </summary>
        internal static string EliminarCliente {
            get {
                return ResourceManager.GetString("EliminarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al exportar.
        /// </summary>
        internal static string ErrorAlExportar {
            get {
                return ResourceManager.GetString("ErrorAlExportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al importar cliente:.
        /// </summary>
        internal static string ErrorAlImportar {
            get {
                return ResourceManager.GetString("ErrorAlImportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar.
        /// </summary>
        internal static string Exportar {
            get {
                return ResourceManager.GetString("Exportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar clientes.
        /// </summary>
        internal static string ExportarClientes {
            get {
                return ResourceManager.GetString("ExportarClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar cliente.
        /// </summary>
        internal static string ImportarCliente {
            get {
                return ResourceManager.GetString("ImportarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informes.
        /// </summary>
        internal static string Informes {
            get {
                return ResourceManager.GetString("Informes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimiento.
        /// </summary>
        internal static string Mantenimiento {
            get {
                return ResourceManager.GetString("Mantenimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú principal.
        /// </summary>
        internal static string Menu_principal {
            get {
                return ResourceManager.GetString("Menu_principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo cliente.
        /// </summary>
        internal static string NuevoCliente {
            get {
                return ResourceManager.GetString("NuevoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable.
        /// </summary>
        internal static string Responsable {
            get {
                return ResourceManager.GetString("Responsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string Salir {
            get {
                return ResourceManager.GetString("Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SapId.
        /// </summary>
        internal static string SapId {
            get {
                return ResourceManager.GetString("SapId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se han exportado .
        /// </summary>
        internal static string SeHanExportado {
            get {
                return ResourceManager.GetString("SeHanExportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionados.
        /// </summary>
        internal static string Seleccionados {
            get {
                return ResourceManager.GetString("Seleccionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar clientes para exportar.
        /// </summary>
        internal static string SeleccionarClientes {
            get {
                return ResourceManager.GetString("SeleccionarClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar todos.
        /// </summary>
        internal static string SeleccionarTodos {
            get {
                return ResourceManager.GetString("SeleccionarTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione al menos un cliente..
        /// </summary>
        internal static string SeleccioneUnCliente {
            get {
                return ResourceManager.GetString("SeleccioneUnCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total: .
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver resumen.
        /// </summary>
        internal static string VerResumen {
            get {
                return ResourceManager.GetString("VerResumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión de los datos:.
        /// </summary>
        internal static string Version_datos {
            get {
                return ResourceManager.GetString("Version_datos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver al menú principal.
        /// </summary>
        internal static string VolverMenu {
            get {
                return ResourceManager.GetString("VolverMenu", resourceCulture);
            }
        }
    }
}
