//------------------------------------------------------------------------------
// <auto-generated>
//     Generado por una herramienta.
//     Los cambios en este fichero pueden causar un comportamiento incorrecto y se
//     perderán si el código se vuelve a generar.
//
//     Escrito a mano siguiendo exactamente el patrón que produce
//     ResXFileCodeGenerator, para no depender de que Visual Studio lo regenere.
//     Si en Visual Studio se edita MenuTextos.resx y se guarda, esta clase se
//     puede regenerar automáticamente sin problema (mismo namespace/nombres).
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotoGestionClientes.UI.Resources
{
    using System;
    using System.Reflection;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuTextos
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuTextos()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RotoGestionClientes.UI.Resources.MenuTextos", typeof(MenuTextos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string MenuPrincipal => ResourceManager.GetString("MenuPrincipal", resourceCulture)!;

        public static string Clientes => ResourceManager.GetString("Clientes", resourceCulture)!;

        public static string Mantenimiento => ResourceManager.GetString("Mantenimiento", resourceCulture)!;

        public static string Informes => ResourceManager.GetString("Informes", resourceCulture)!;

        public static string CrearActualizacion => ResourceManager.GetString("CrearActualizacion", resourceCulture)!;

        public static string ActualizarDatos => ResourceManager.GetString("ActualizarDatos", resourceCulture)!;

        public static string Salir => ResourceManager.GetString("Salir", resourceCulture)!;

        public static string VersionDatos => ResourceManager.GetString("VersionDatos", resourceCulture)!;

        public static string ProximamenteTitulo => ResourceManager.GetString("ProximamenteTitulo", resourceCulture)!;

        public static string ProximamenteTexto => ResourceManager.GetString("ProximamenteTexto", resourceCulture)!;

        public static string Bienvenida => ResourceManager.GetString("Bienvenida", resourceCulture)!;

        public static string BienvenidaTexto => ResourceManager.GetString("BienvenidaTexto", resourceCulture)!;
    }
}
