//------------------------------------------------------------------------------
// <auto-generated>
//     Generado por una herramienta.
//     Los cambios en este fichero pueden causar un comportamiento incorrecto y se
//     perderán si el código se vuelve a generar.
//
//     Escrito a mano siguiendo exactamente el patrón que produce
//     ResXFileCodeGenerator, para no depender de que Visual Studio lo regenere.
//     Si en Visual Studio se edita MenuTextos.resx y se guarda, esta clase se
//     puede regenerar automáticamente sin problema (mismo namespace/nombres).
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotoGestionClientes.UI.Resources
{
    using System;
    using System.Reflection;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuTextos
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuTextos()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RotoGestionClientes.UI.Resources.MenuTextos", typeof(MenuTextos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string MenuPrincipal => ResourceManager.GetString("MenuPrincipal", resourceCulture)!;

        public static string Clientes => ResourceManager.GetString("Clientes", resourceCulture)!;

        public static string Mantenimiento => ResourceManager.GetString("Mantenimiento", resourceCulture)!;

        public static string Informes => ResourceManager.GetString("Informes", resourceCulture)!;

        public static string CrearActualizacion => ResourceManager.GetString("CrearActualizacion", resourceCulture)!;

        public static string ActualizarDatos => ResourceManager.GetString("ActualizarDatos", resourceCulture)!;

        public static string Salir => ResourceManager.GetString("Salir", resourceCulture)!;

        public static string VersionDatos => ResourceManager.GetString("VersionDatos", resourceCulture)!;

        public static string ProximamenteTitulo => ResourceManager.GetString("ProximamenteTitulo", resourceCulture)!;

        public static string ProximamenteTexto => ResourceManager.GetString("ProximamenteTexto", resourceCulture)!;

        public static string Bienvenida => ResourceManager.GetString("Bienvenida", resourceCulture)!;

        public static string BienvenidaTexto => ResourceManager.GetString("BienvenidaTexto", resourceCulture)!;

        public static string NuevoCliente => ResourceManager.GetString("NuevoCliente", resourceCulture)!;

        public static string ImportarCliente => ResourceManager.GetString("ImportarCliente", resourceCulture)!;

        public static string ExportarClientes => ResourceManager.GetString("ExportarClientes", resourceCulture)!;

        public static string VolverMenu => ResourceManager.GetString("VolverMenu", resourceCulture)!;

        public static string Total => ResourceManager.GetString("Total", resourceCulture)!;

        public static string Buscar => ResourceManager.GetString("Buscar", resourceCulture)!;

        public static string SapId => ResourceManager.GetString("SapId", resourceCulture)!;

        public static string Nombre => ResourceManager.GetString("Nombre", resourceCulture)!;

        public static string Responsable => ResourceManager.GetString("Responsable", resourceCulture)!;

        public static string Comentarios => ResourceManager.GetString("Comentarios", resourceCulture)!;

        public static string Acciones => ResourceManager.GetString("Acciones", resourceCulture)!;

        public static string VerResumen => ResourceManager.GetString("VerResumen", resourceCulture)!;

        public static string Editar => ResourceManager.GetString("Editar", resourceCulture)!;

        public static string Exportar => ResourceManager.GetString("Exportar", resourceCulture)!;

        public static string CrearConfigurador => ResourceManager.GetString("CrearConfigurador", resourceCulture)!;

        public static string Eliminar => ResourceManager.GetString("Eliminar", resourceCulture)!;

        public static string EliminarClienteTitulo => ResourceManager.GetString("EliminarClienteTitulo", resourceCulture)!;

        public static string ConfirmarEliminarCliente => ResourceManager.GetString("ConfirmarEliminarCliente", resourceCulture)!;

        public static string SinResultados => ResourceManager.GetString("SinResultados", resourceCulture)!;

        public static string SinMaquinas => ResourceManager.GetString("SinMaquinas", resourceCulture)!;

        public static string SinDocumentos => ResourceManager.GetString("SinDocumentos", resourceCulture)!;

        public static string Cancelar => ResourceManager.GetString("Cancelar", resourceCulture)!;

        public static string Atras => ResourceManager.GetString("Atras", resourceCulture)!;

        public static string Siguiente => ResourceManager.GetString("Siguiente", resourceCulture)!;

        public static string Finalizar => ResourceManager.GetString("Finalizar", resourceCulture)!;

        public static string Guardar => ResourceManager.GetString("Guardar", resourceCulture)!;

        public static string EditandoCliente => ResourceManager.GetString("EditandoCliente", resourceCulture)!;

        public static string CompletarDatosCliente => ResourceManager.GetString("CompletarDatosCliente", resourceCulture)!;

        public static string DatosGenerales => ResourceManager.GetString("DatosGenerales", resourceCulture)!;

        public static string Ventanas => ResourceManager.GetString("Ventanas", resourceCulture)!;

        public static string Balconeras => ResourceManager.GetString("Balconeras", resourceCulture)!;

        public static string Puertas => ResourceManager.GetString("Puertas", resourceCulture)!;

        public static string Correderas => ResourceManager.GetString("Correderas", resourceCulture)!;

        public static string Bombillo => ResourceManager.GetString("Bombillo", resourceCulture)!;

        public static string ElevablesPlegables => ResourceManager.GetString("ElevablesPlegables", resourceCulture)!;

        public static string Elevables => ResourceManager.GetString("Elevables", resourceCulture)!;

        public static string Plegables => ResourceManager.GetString("Plegables", resourceCulture)!;

        public static string Estandar => ResourceManager.GetString("Estandar", resourceCulture)!;

        public static string Dlo => ResourceManager.GetString("Dlo", resourceCulture)!;

        public static string Consumen => ResourceManager.GetString("Consumen", resourceCulture)!;

        public static string Maquinas => ResourceManager.GetString("Maquinas", resourceCulture)!;

        public static string Documentos => ResourceManager.GetString("Documentos", resourceCulture)!;

        public static string Documento => ResourceManager.GetString("Documento", resourceCulture)!;

        public static string DocumentoObligatorio => ResourceManager.GetString("DocumentoObligatorio", resourceCulture)!;

        public static string Fichero => ResourceManager.GetString("Fichero", resourceCulture)!;

        public static string IndicarNombreDoc => ResourceManager.GetString("IndicarNombreDoc", resourceCulture)!;

        public static string NingunFichero => ResourceManager.GetString("NingunFichero", resourceCulture)!;

        public static string NombreDocumento => ResourceManager.GetString("NombreDocumento", resourceCulture)!;

        public static string SeleccionarDocumento => ResourceManager.GetString("SeleccionarDocumento", resourceCulture)!;

        public static string AnadirDocumento => ResourceManager.GetString("AnadirDocumento", resourceCulture)!;

        public static string EliminarDocumentoTitulo => ResourceManager.GetString("EliminarDocumentoTitulo", resourceCulture)!;

        public static string ConfirmarEliminarDocumento => ResourceManager.GetString("ConfirmarEliminarDocumento", resourceCulture)!;

        public static string DebeGuardarClienteDescarga => ResourceManager.GetString("DebeGuardarClienteDescarga", resourceCulture)!;

        public static string DocumentoNoEncontrado => ResourceManager.GetString("DocumentoNoEncontrado", resourceCulture)!;

        public static string DocumentoDescargado => ResourceManager.GetString("DocumentoDescargado", resourceCulture)!;

        public static string DatosCorruptos => ResourceManager.GetString("DatosCorruptos", resourceCulture)!;

        public static string ClienteExistente => ResourceManager.GetString("ClienteExistente", resourceCulture)!;

        public static string NombreClienteObligatorio => ResourceManager.GetString("NombreClienteObligatorio", resourceCulture)!;

        public static string ClienteCreado => ResourceManager.GetString("ClienteCreado", resourceCulture)!;

        public static string ClienteActualizado => ResourceManager.GetString("ClienteActualizado", resourceCulture)!;

        public static string Software => ResourceManager.GetString("Software", resourceCulture)!;

        public static string SoporteCompas => ResourceManager.GetString("SoporteCompas", resourceCulture)!;

        public static string TipoPerfil => ResourceManager.GetString("TipoPerfil", resourceCulture)!;

        public static string Perfil => ResourceManager.GetString("Perfil", resourceCulture)!;

        public static string Manillas => ResourceManager.GetString("Manillas", resourceCulture)!;

        public static string Alias => ResourceManager.GetString("Alias", resourceCulture)!;

        public static string SeleccionaTipoPerfil => ResourceManager.GetString("SeleccionaTipoPerfil", resourceCulture)!;

        public static string PasoProximamenteTexto => ResourceManager.GetString("PasoProximamenteTexto", resourceCulture)!;

        public static string Oscilobatientes => ResourceManager.GetString("Oscilobatientes", resourceCulture)!;

        public static string Seguridad => ResourceManager.GetString("Seguridad", resourceCulture)!;

        public static string HojaPasiva => ResourceManager.GetString("HojaPasiva", resourceCulture)!;

        public static string Practicables => ResourceManager.GetString("Practicables", resourceCulture)!;

        public static string PuertaSecundaria => ResourceManager.GetString("PuertaSecundaria", resourceCulture)!;

        public static string Aguja => ResourceManager.GetString("Aguja", resourceCulture)!;

        public static string Todos => ResourceManager.GetString("Todos", resourceCulture)!;

        public static string PorPerfil => ResourceManager.GetString("PorPerfil", resourceCulture)!;

        public static string Bisagras => ResourceManager.GetString("Bisagras", resourceCulture)!;

        public static string Cerraduras => ResourceManager.GetString("Cerraduras", resourceCulture)!;

        public static string DefinirAgujaPerfil => ResourceManager.GetString("DefinirAgujaPerfil", resourceCulture)!;

        public static string ConfigurarPorPerfil => ResourceManager.GetString("ConfigurarPorPerfil", resourceCulture)!;

        public static string Cilindros => ResourceManager.GetString("Cilindros", resourceCulture)!;

        public static string SeleccionarCilindros => ResourceManager.GetString("SeleccionarCilindros", resourceCulture)!;

        public static string ConfigurarCilindros => ResourceManager.GetString("ConfigurarCilindros", resourceCulture)!;

        public static string Tipo => ResourceManager.GetString("Tipo", resourceCulture)!;

        public static string Marca => ResourceManager.GetString("Marca", resourceCulture)!;

        public static string BisagrasSoldadora => ResourceManager.GetString("BisagrasSoldadora", resourceCulture)!;

        public static string TripleTaladroCentro => ResourceManager.GetString("TripleTaladroCentro", resourceCulture)!;

        public static string SoporteMarco => ResourceManager.GetString("SoporteMarco", resourceCulture)!;

        public static string CentroMecanizado => ResourceManager.GetString("CentroMecanizado", resourceCulture)!;

        public static string Plantilla => ResourceManager.GetString("Plantilla", resourceCulture)!;

        public static string BancoMarcos => ResourceManager.GetString("BancoMarcos", resourceCulture)!;

        public static string TipoMaquinaObligatorio => ResourceManager.GetString("TipoMaquinaObligatorio", resourceCulture)!;

        public static string MantenimientoObligatorio => ResourceManager.GetString("MantenimientoObligatorio", resourceCulture)!;

        public static string AnadirMaquina => ResourceManager.GetString("AnadirMaquina", resourceCulture)!;

        public static string EditarMaquina => ResourceManager.GetString("EditarMaquina", resourceCulture)!;

        public static string EliminarMaquinaTitulo => ResourceManager.GetString("EliminarMaquinaTitulo", resourceCulture)!;

        public static string ConfirmarEliminarMaquina => ResourceManager.GetString("ConfirmarEliminarMaquina", resourceCulture)!;

        public static string Interior => ResourceManager.GetString("Interior", resourceCulture)!;

        public static string Exterior => ResourceManager.GetString("Exterior", resourceCulture)!;

        public static string Nomenclatura => ResourceManager.GetString("Nomenclatura", resourceCulture)!;

        public static string Si => ResourceManager.GetString("Si", resourceCulture)!;

        public static string No => ResourceManager.GetString("No", resourceCulture)!;

        public static string Usuarios => ResourceManager.GetString("Usuarios", resourceCulture)!;

        public static string Perfiles => ResourceManager.GetString("Perfiles", resourceCulture)!;

        public static string MarcasMaquinas => ResourceManager.GetString("MarcasMaquinas", resourceCulture)!;

        public static string MantenimientoMaquina => ResourceManager.GetString("MantenimientoMaquina", resourceCulture)!;

        public static string TipoMaquinas => ResourceManager.GetString("TipoMaquinas", resourceCulture)!;

        public static string SeguridadVentana => ResourceManager.GetString("SeguridadVentana", resourceCulture)!;

        public static string Pasivas => ResourceManager.GetString("Pasivas", resourceCulture)!;

        public static string Activo => ResourceManager.GetString("Activo", resourceCulture)!;

        public static string EsDistribuidor => ResourceManager.GetString("EsDistribuidor", resourceCulture)!;

        public static string NombreObligatorio => ResourceManager.GetString("NombreObligatorio", resourceCulture)!;

        public static string Nuevo => ResourceManager.GetString("Nuevo", resourceCulture)!;

        public static string TipoPerfilObligatorio => ResourceManager.GetString("TipoPerfilObligatorio", resourceCulture)!;

        public static string SeleccionaCategoria => ResourceManager.GetString("SeleccionaCategoria", resourceCulture)!;
    }
}
