//------------------------------------------------------------------------------
// <auto-generated>
//     Generado por una herramienta.
//     Los cambios en este fichero pueden causar un comportamiento incorrecto y se
//     perderán si el código se vuelve a generar.
//
//     Escrito a mano siguiendo exactamente el patrón que produce
//     ResXFileCodeGenerator, para no depender de que Visual Studio lo regenere.
//     Si en Visual Studio se edita MenuTextos.resx y se guarda, esta clase se
//     puede regenerar automáticamente sin problema (mismo namespace/nombres).
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotoGestionClientes.UI.Resources
{
    using System;
    using System.Reflection;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuTextos
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuTextos()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RotoGestionClientes.UI.Resources.MenuTextos", typeof(MenuTextos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string MenuPrincipal => ResourceManager.GetString("MenuPrincipal", resourceCulture)!;

        public static string Clientes => ResourceManager.GetString("Clientes", resourceCulture)!;

        public static string Mantenimiento => ResourceManager.GetString("Mantenimiento", resourceCulture)!;

        public static string Informes => ResourceManager.GetString("Informes", resourceCulture)!;

        public static string CrearActualizacion => ResourceManager.GetString("CrearActualizacion", resourceCulture)!;

        public static string ActualizarDatos => ResourceManager.GetString("ActualizarDatos", resourceCulture)!;

        public static string Salir => ResourceManager.GetString("Salir", resourceCulture)!;

        public static string VersionDatos => ResourceManager.GetString("VersionDatos", resourceCulture)!;

        public static string ProximamenteTitulo => ResourceManager.GetString("ProximamenteTitulo", resourceCulture)!;

        public static string ProximamenteTexto => ResourceManager.GetString("ProximamenteTexto", resourceCulture)!;

        public static string Bienvenida => ResourceManager.GetString("Bienvenida", resourceCulture)!;

        public static string BienvenidaTexto => ResourceManager.GetString("BienvenidaTexto", resourceCulture)!;

        public static string AccesosRapidos => ResourceManager.GetString("AccesosRapidos", resourceCulture)!;

        public static string VersionApp => ResourceManager.GetString("VersionApp", resourceCulture)!;

        public static string TotalClientes => ResourceManager.GetString("TotalClientes", resourceCulture)!;

        public static string AccesoTipoPerfilPVC => ResourceManager.GetString("AccesoTipoPerfilPVC", resourceCulture)!;

        public static string AccesoTipoPerfilAluminio => ResourceManager.GetString("AccesoTipoPerfilAluminio", resourceCulture)!;

        public static string AccesoMaquinasMesaHerraje => ResourceManager.GetString("AccesoMaquinasMesaHerraje", resourceCulture)!;

        public static string NuevoCliente => ResourceManager.GetString("NuevoCliente", resourceCulture)!;

        public static string ImportarCliente => ResourceManager.GetString("ImportarCliente", resourceCulture)!;

        public static string ExportarClientes => ResourceManager.GetString("ExportarClientes", resourceCulture)!;

        public static string VolverMenu => ResourceManager.GetString("VolverMenu", resourceCulture)!;

        public static string Total => ResourceManager.GetString("Total", resourceCulture)!;

        public static string Buscar => ResourceManager.GetString("Buscar", resourceCulture)!;

        public static string SapId => ResourceManager.GetString("SapId", resourceCulture)!;

        public static string Nombre => ResourceManager.GetString("Nombre", resourceCulture)!;

        public static string Responsable => ResourceManager.GetString("Responsable", resourceCulture)!;

        public static string Comentarios => ResourceManager.GetString("Comentarios", resourceCulture)!;

        public static string Acciones => ResourceManager.GetString("Acciones", resourceCulture)!;

        public static string VerResumen => ResourceManager.GetString("VerResumen", resourceCulture)!;

        public static string Editar => ResourceManager.GetString("Editar", resourceCulture)!;

        public static string Exportar => ResourceManager.GetString("Exportar", resourceCulture)!;

        public static string CrearConfigurador => ResourceManager.GetString("CrearConfigurador", resourceCulture)!;

        public static string Eliminar => ResourceManager.GetString("Eliminar", resourceCulture)!;

        public static string EliminarClienteTitulo => ResourceManager.GetString("EliminarClienteTitulo", resourceCulture)!;

        public static string ConfirmarEliminarCliente => ResourceManager.GetString("ConfirmarEliminarCliente", resourceCulture)!;

        public static string SinResultados => ResourceManager.GetString("SinResultados", resourceCulture)!;

        public static string SinMaquinas => ResourceManager.GetString("SinMaquinas", resourceCulture)!;

        public static string SinDocumentos => ResourceManager.GetString("SinDocumentos", resourceCulture)!;

        public static string Cancelar => ResourceManager.GetString("Cancelar", resourceCulture)!;

        public static string Atras => ResourceManager.GetString("Atras", resourceCulture)!;

        public static string Siguiente => ResourceManager.GetString("Siguiente", resourceCulture)!;

        public static string Finalizar => ResourceManager.GetString("Finalizar", resourceCulture)!;

        public static string Guardar => ResourceManager.GetString("Guardar", resourceCulture)!;

        public static string EditandoCliente => ResourceManager.GetString("EditandoCliente", resourceCulture)!;

        public static string CompletarDatosCliente => ResourceManager.GetString("CompletarDatosCliente", resourceCulture)!;

        public static string DatosGenerales => ResourceManager.GetString("DatosGenerales", resourceCulture)!;

        public static string Ventanas => ResourceManager.GetString("Ventanas", resourceCulture)!;

        public static string Balconeras => ResourceManager.GetString("Balconeras", resourceCulture)!;

        public static string Puertas => ResourceManager.GetString("Puertas", resourceCulture)!;

        public static string Correderas => ResourceManager.GetString("Correderas", resourceCulture)!;

        public static string Bombillo => ResourceManager.GetString("Bombillo", resourceCulture)!;

        public static string ElevablesPlegables => ResourceManager.GetString("ElevablesPlegables", resourceCulture)!;

        public static string Elevables => ResourceManager.GetString("Elevables", resourceCulture)!;

        public static string Plegables => ResourceManager.GetString("Plegables", resourceCulture)!;

        public static string Estandar => ResourceManager.GetString("Estandar", resourceCulture)!;

        public static string Dlo => ResourceManager.GetString("Dlo", resourceCulture)!;

        public static string Consumen => ResourceManager.GetString("Consumen", resourceCulture)!;

        public static string Maquinas => ResourceManager.GetString("Maquinas", resourceCulture)!;

        public static string Documentos => ResourceManager.GetString("Documentos", resourceCulture)!;

        public static string Documento => ResourceManager.GetString("Documento", resourceCulture)!;

        public static string DocumentoObligatorio => ResourceManager.GetString("DocumentoObligatorio", resourceCulture)!;

        public static string Fichero => ResourceManager.GetString("Fichero", resourceCulture)!;

        public static string IndicarNombreDoc => ResourceManager.GetString("IndicarNombreDoc", resourceCulture)!;

        public static string NingunFichero => ResourceManager.GetString("NingunFichero", resourceCulture)!;

        public static string NombreDocumento => ResourceManager.GetString("NombreDocumento", resourceCulture)!;

        public static string SeleccionarDocumento => ResourceManager.GetString("SeleccionarDocumento", resourceCulture)!;

        public static string AnadirDocumento => ResourceManager.GetString("AnadirDocumento", resourceCulture)!;

        public static string EliminarDocumentoTitulo => ResourceManager.GetString("EliminarDocumentoTitulo", resourceCulture)!;

        public static string ConfirmarEliminarDocumento => ResourceManager.GetString("ConfirmarEliminarDocumento", resourceCulture)!;

        public static string DebeGuardarClienteDescarga => ResourceManager.GetString("DebeGuardarClienteDescarga", resourceCulture)!;

        public static string DocumentoNoEncontrado => ResourceManager.GetString("DocumentoNoEncontrado", resourceCulture)!;

        public static string DocumentoDescargado => ResourceManager.GetString("DocumentoDescargado", resourceCulture)!;

        public static string DatosCorruptos => ResourceManager.GetString("DatosCorruptos", resourceCulture)!;

        public static string ClienteExistente => ResourceManager.GetString("ClienteExistente", resourceCulture)!;

        public static string NombreClienteObligatorio => ResourceManager.GetString("NombreClienteObligatorio", resourceCulture)!;

        public static string ClienteCreado => ResourceManager.GetString("ClienteCreado", resourceCulture)!;

        public static string ClienteActualizado => ResourceManager.GetString("ClienteActualizado", resourceCulture)!;

        public static string Software => ResourceManager.GetString("Software", resourceCulture)!;

        public static string SoporteCompas => ResourceManager.GetString("SoporteCompas", resourceCulture)!;

        public static string TipoPerfil => ResourceManager.GetString("TipoPerfil", resourceCulture)!;

        public static string Perfil => ResourceManager.GetString("Perfil", resourceCulture)!;

        public static string Manillas => ResourceManager.GetString("Manillas", resourceCulture)!;

        public static string Alias => ResourceManager.GetString("Alias", resourceCulture)!;

        public static string SeleccionaTipoPerfil => ResourceManager.GetString("SeleccionaTipoPerfil", resourceCulture)!;

        public static string PasoProximamenteTexto => ResourceManager.GetString("PasoProximamenteTexto", resourceCulture)!;

        public static string Oscilobatientes => ResourceManager.GetString("Oscilobatientes", resourceCulture)!;

        public static string Seguridad => ResourceManager.GetString("Seguridad", resourceCulture)!;

        public static string HojaPasiva => ResourceManager.GetString("HojaPasiva", resourceCulture)!;

        public static string Practicables => ResourceManager.GetString("Practicables", resourceCulture)!;

        public static string PuertaSecundaria => ResourceManager.GetString("PuertaSecundaria", resourceCulture)!;

        public static string Aguja => ResourceManager.GetString("Aguja", resourceCulture)!;

        public static string Todos => ResourceManager.GetString("Todos", resourceCulture)!;

        public static string PorPerfil => ResourceManager.GetString("PorPerfil", resourceCulture)!;

        public static string Bisagras => ResourceManager.GetString("Bisagras", resourceCulture)!;

        public static string Cerraduras => ResourceManager.GetString("Cerraduras", resourceCulture)!;

        public static string DefinirAgujaPerfil => ResourceManager.GetString("DefinirAgujaPerfil", resourceCulture)!;

        public static string ConfigurarPorPerfil => ResourceManager.GetString("ConfigurarPorPerfil", resourceCulture)!;

        public static string Cilindros => ResourceManager.GetString("Cilindros", resourceCulture)!;

        public static string SeleccionarCilindros => ResourceManager.GetString("SeleccionarCilindros", resourceCulture)!;

        public static string ConfigurarCilindros => ResourceManager.GetString("ConfigurarCilindros", resourceCulture)!;

        public static string Tipo => ResourceManager.GetString("Tipo", resourceCulture)!;

        public static string Marca => ResourceManager.GetString("Marca", resourceCulture)!;

        public static string BisagrasSoldadora => ResourceManager.GetString("BisagrasSoldadora", resourceCulture)!;

        public static string TripleTaladroCentro => ResourceManager.GetString("TripleTaladroCentro", resourceCulture)!;

        public static string SoporteMarco => ResourceManager.GetString("SoporteMarco", resourceCulture)!;

        public static string CentroMecanizado => ResourceManager.GetString("CentroMecanizado", resourceCulture)!;

        public static string Plantilla => ResourceManager.GetString("Plantilla", resourceCulture)!;

        public static string BancoMarcos => ResourceManager.GetString("BancoMarcos", resourceCulture)!;

        public static string TipoMaquinaObligatorio => ResourceManager.GetString("TipoMaquinaObligatorio", resourceCulture)!;

        public static string MantenimientoObligatorio => ResourceManager.GetString("MantenimientoObligatorio", resourceCulture)!;

        public static string AnadirMaquina => ResourceManager.GetString("AnadirMaquina", resourceCulture)!;

        public static string EditarMaquina => ResourceManager.GetString("EditarMaquina", resourceCulture)!;

        public static string EliminarMaquinaTitulo => ResourceManager.GetString("EliminarMaquinaTitulo", resourceCulture)!;

        public static string ConfirmarEliminarMaquina => ResourceManager.GetString("ConfirmarEliminarMaquina", resourceCulture)!;

        public static string Interior => ResourceManager.GetString("Interior", resourceCulture)!;

        public static string Exterior => ResourceManager.GetString("Exterior", resourceCulture)!;

        public static string Nomenclatura => ResourceManager.GetString("Nomenclatura", resourceCulture)!;

        public static string Si => ResourceManager.GetString("Si", resourceCulture)!;

        public static string No => ResourceManager.GetString("No", resourceCulture)!;

        public static string Usuarios => ResourceManager.GetString("Usuarios", resourceCulture)!;

        public static string Perfiles => ResourceManager.GetString("Perfiles", resourceCulture)!;

        public static string MarcasMaquinas => ResourceManager.GetString("MarcasMaquinas", resourceCulture)!;

        public static string MantenimientoMaquina => ResourceManager.GetString("MantenimientoMaquina", resourceCulture)!;

        public static string TipoMaquinas => ResourceManager.GetString("TipoMaquinas", resourceCulture)!;

        public static string SeguridadVentana => ResourceManager.GetString("SeguridadVentana", resourceCulture)!;

        public static string Pasivas => ResourceManager.GetString("Pasivas", resourceCulture)!;

        public static string Activo => ResourceManager.GetString("Activo", resourceCulture)!;

        public static string EsDistribuidor => ResourceManager.GetString("EsDistribuidor", resourceCulture)!;

        public static string NombreObligatorio => ResourceManager.GetString("NombreObligatorio", resourceCulture)!;

        public static string Nuevo => ResourceManager.GetString("Nuevo", resourceCulture)!;

        public static string TipoPerfilObligatorio => ResourceManager.GetString("TipoPerfilObligatorio", resourceCulture)!;

        public static string SeleccionaCategoria => ResourceManager.GetString("SeleccionaCategoria", resourceCulture)!;

        public static string TotalRegistros => ResourceManager.GetString("TotalRegistros", resourceCulture)!;

        public static string LimpiarFiltros => ResourceManager.GetString("LimpiarFiltros", resourceCulture)!;

        public static string ExportarExcel => ResourceManager.GetString("ExportarExcel", resourceCulture)!;

        public static string NoDatosExportar => ResourceManager.GetString("NoDatosExportar", resourceCulture)!;

        public static string ExcelExportadoCorrectamente => ResourceManager.GetString("ExcelExportadoCorrectamente", resourceCulture)!;

        public static string Seleccionar => ResourceManager.GetString("Seleccionar", resourceCulture)!;

        public static string Responsables => ResourceManager.GetString("Responsables", resourceCulture)!;

        public static string Softwares => ResourceManager.GetString("Softwares", resourceCulture)!;

        public static string CrearActualizacionDescripcion => ResourceManager.GetString("CrearActualizacionDescripcion", resourceCulture)!;

        public static string ActualizarDatosDescripcion => ResourceManager.GetString("ActualizarDatosDescripcion", resourceCulture)!;

        public static string SeleccionarArchivoActualizacion => ResourceManager.GetString("SeleccionarArchivoActualizacion", resourceCulture)!;

        public static string AplicarActualizacion => ResourceManager.GetString("AplicarActualizacion", resourceCulture)!;

        public static string ArchivoActualizacionObligatorio => ResourceManager.GetString("ArchivoActualizacionObligatorio", resourceCulture)!;

        public static string DatosExportadosCorrectamente => ResourceManager.GetString("DatosExportadosCorrectamente", resourceCulture)!;

        public static string ErrorExportarDatos => ResourceManager.GetString("ErrorExportarDatos", resourceCulture)!;

        public static string ErrorImportarDatos => ResourceManager.GetString("ErrorImportarDatos", resourceCulture)!;

        public static string DatosActualizadosVersion => ResourceManager.GetString("DatosActualizadosVersion", resourceCulture)!;

        public static string SeleccionarClientes => ResourceManager.GetString("SeleccionarClientes", resourceCulture)!;

        public static string SeleccionarTodos => ResourceManager.GetString("SeleccionarTodos", resourceCulture)!;

        public static string Seleccionados => ResourceManager.GetString("Seleccionados", resourceCulture)!;

        public static string SeleccioneUnCliente => ResourceManager.GetString("SeleccioneUnCliente", resourceCulture)!;

        public static string ClienteExportado => ResourceManager.GetString("ClienteExportado", resourceCulture)!;

        public static string ClienteNoEncontrado => ResourceManager.GetString("ClienteNoEncontrado", resourceCulture)!;

        public static string ErrorAlExportar => ResourceManager.GetString("ErrorAlExportar", resourceCulture)!;

        public static string ClientesExportadosCorrectamente => ResourceManager.GetString("ClientesExportadosCorrectamente", resourceCulture)!;

        public static string De => ResourceManager.GetString("De", resourceCulture)!;

        public static string ImportarClienteDescripcion => ResourceManager.GetString("ImportarClienteDescripcion", resourceCulture)!;

        public static string SeleccionarArchivoImportacion => ResourceManager.GetString("SeleccionarArchivoImportacion", resourceCulture)!;

        public static string FormatoArchivoNoValido => ResourceManager.GetString("FormatoArchivoNoValido", resourceCulture)!;

        public static string ZipSinFicherosRoto => ResourceManager.GetString("ZipSinFicherosRoto", resourceCulture)!;

        public static string SeleccionarFicheroObligatorio => ResourceManager.GetString("SeleccionarFicheroObligatorio", resourceCulture)!;

        public static string ArchivoNoValido => ResourceManager.GetString("ArchivoNoValido", resourceCulture)!;

        public static string ClienteImportado => ResourceManager.GetString("ClienteImportado", resourceCulture)!;

        public static string ErrorAlImportar => ResourceManager.GetString("ErrorAlImportar", resourceCulture)!;

        public static string NombreAsignado => ResourceManager.GetString("NombreAsignado", resourceCulture)!;

        public static string ClienteExistenteImportado => ResourceManager.GetString("ClienteExistenteImportado", resourceCulture)!;

        public static string ArchivoGeneradoCorrectamente => ResourceManager.GetString("ArchivoGeneradoCorrectamente", resourceCulture)!;

        public static string ErrorGenerarConfig => ResourceManager.GetString("ErrorGenerarConfig", resourceCulture)!;

        public static string ExportarPdf => ResourceManager.GetString("ExportarPdf", resourceCulture)!;

        public static string PdfGeneradoCorrectamente => ResourceManager.GetString("PdfGeneradoCorrectamente", resourceCulture)!;

        public static string ErrorGenerarPdf => ResourceManager.GetString("ErrorGenerarPdf", resourceCulture)!;

        public static string Cerrar => ResourceManager.GetString("Cerrar", resourceCulture)!;

        public static string ClientesImportadosCorrectamente => ResourceManager.GetString("ClientesImportadosCorrectamente", resourceCulture)!;

        public static string ResumenCliente => ResourceManager.GetString("ResumenCliente", resourceCulture)!;

        public static string VolverListado => ResourceManager.GetString("VolverListado", resourceCulture)!;

        public static string PorteroElectrico => ResourceManager.GetString("PorteroElectrico", resourceCulture)!;

        public static string Ninguno => ResourceManager.GetString("Ninguno", resourceCulture)!;

        public static string ObservacionesParalelas => ResourceManager.GetString("ObservacionesParalelas", resourceCulture)!;

        public static string UsuarioLogin => ResourceManager.GetString("UsuarioLogin", resourceCulture)!;

        public static string Contrasena => ResourceManager.GetString("Contrasena", resourceCulture)!;

        public static string Entrar => ResourceManager.GetString("Entrar", resourceCulture)!;

        public static string CerrarSesion => ResourceManager.GetString("CerrarSesion", resourceCulture)!;

        public static string NuevaContrasena => ResourceManager.GetString("NuevaContrasena", resourceCulture)!;

        public static string ConfirmarContrasena => ResourceManager.GetString("ConfirmarContrasena", resourceCulture)!;

        public static string GuardarContrasena => ResourceManager.GetString("GuardarContrasena", resourceCulture)!;

        public static string DebeCambiarPasswordTexto => ResourceManager.GetString("DebeCambiarPasswordTexto", resourceCulture)!;

        public static string CredencialesIncompletas => ResourceManager.GetString("CredencialesIncompletas", resourceCulture)!;

        public static string CredencialesIncorrectas => ResourceManager.GetString("CredencialesIncorrectas", resourceCulture)!;

        public static string PasswordDemasiadoCorta => ResourceManager.GetString("PasswordDemasiadoCorta", resourceCulture)!;

        public static string PasswordsNoCoinciden => ResourceManager.GetString("PasswordsNoCoinciden", resourceCulture)!;

        public static string ErrorGenerico => ResourceManager.GetString("ErrorGenerico", resourceCulture)!;

        public static string Auditoria => ResourceManager.GetString("Auditoria", resourceCulture)!;

        public static string AccionCrear => ResourceManager.GetString("AccionCrear", resourceCulture)!;

        public static string AccionModificar => ResourceManager.GetString("AccionModificar", resourceCulture)!;

        public static string AccionEliminar => ResourceManager.GetString("AccionEliminar", resourceCulture)!;

        public static string Entidad => ResourceManager.GetString("Entidad", resourceCulture)!;

        public static string Accion => ResourceManager.GetString("Accion", resourceCulture)!;

        public static string FechaHora => ResourceManager.GetString("FechaHora", resourceCulture)!;

        public static string Detalle => ResourceManager.GetString("Detalle", resourceCulture)!;

        public static string FechaDesde => ResourceManager.GetString("FechaDesde", resourceCulture)!;

        public static string FechaHasta => ResourceManager.GetString("FechaHasta", resourceCulture)!;

        public static string UsuarioFiltro => ResourceManager.GetString("UsuarioFiltro", resourceCulture)!;

        public static string AuditoriaLimiteAviso => ResourceManager.GetString("AuditoriaLimiteAviso", resourceCulture)!;

        public static string CuentasUsuario => ResourceManager.GetString("CuentasUsuario", resourceCulture)!;

        public static string NuevaCuenta => ResourceManager.GetString("NuevaCuenta", resourceCulture)!;

        public static string NombreMostrado => ResourceManager.GetString("NombreMostrado", resourceCulture)!;

        public static string Rol => ResourceManager.GetString("Rol", resourceCulture)!;

        public static string RolAdministrador => ResourceManager.GetString("RolAdministrador", resourceCulture)!;

        public static string RolUsuario => ResourceManager.GetString("RolUsuario", resourceCulture)!;

        public static string Estado => ResourceManager.GetString("Estado", resourceCulture)!;

        public static string CuentaActiva => ResourceManager.GetString("CuentaActiva", resourceCulture)!;

        public static string CuentaInactiva => ResourceManager.GetString("CuentaInactiva", resourceCulture)!;

        public static string CuentaPropia => ResourceManager.GetString("CuentaPropia", resourceCulture)!;

        public static string FechaCreacion => ResourceManager.GetString("FechaCreacion", resourceCulture)!;

        public static string PendienteCambioPassword => ResourceManager.GetString("PendienteCambioPassword", resourceCulture)!;

        public static string ResetearPassword => ResourceManager.GetString("ResetearPassword", resourceCulture)!;

        public static string ResetearPasswordTexto => ResourceManager.GetString("ResetearPasswordTexto", resourceCulture)!;

        public static string PasswordTemporal => ResourceManager.GetString("PasswordTemporal", resourceCulture)!;

        public static string ConfirmarPasswordTemporal => ResourceManager.GetString("ConfirmarPasswordTemporal", resourceCulture)!;

        public static string PasswordReseteada => ResourceManager.GetString("PasswordReseteada", resourceCulture)!;

        public static string Activar => ResourceManager.GetString("Activar", resourceCulture)!;

        public static string Desactivar => ResourceManager.GetString("Desactivar", resourceCulture)!;

        public static string ActivarCuentaTitulo => ResourceManager.GetString("ActivarCuentaTitulo", resourceCulture)!;

        public static string DesactivarCuentaTitulo => ResourceManager.GetString("DesactivarCuentaTitulo", resourceCulture)!;

        public static string ConfirmarActivarCuenta => ResourceManager.GetString("ConfirmarActivarCuenta", resourceCulture)!;

        public static string ConfirmarDesactivarCuenta => ResourceManager.GetString("ConfirmarDesactivarCuenta", resourceCulture)!;

        public static string EliminarCuentaTitulo => ResourceManager.GetString("EliminarCuentaTitulo", resourceCulture)!;

        public static string ConfirmarEliminarCuenta => ResourceManager.GetString("ConfirmarEliminarCuenta", resourceCulture)!;

        public static string CuentaCreada => ResourceManager.GetString("CuentaCreada", resourceCulture)!;

        public static string CuentaActualizada => ResourceManager.GetString("CuentaActualizada", resourceCulture)!;

        public static string CuentaEliminada => ResourceManager.GetString("CuentaEliminada", resourceCulture)!;

        public static string LoginObligatorio => ResourceManager.GetString("LoginObligatorio", resourceCulture)!;

        public static string LoginYaExiste => ResourceManager.GetString("LoginYaExiste", resourceCulture)!;

        public static string NoPuedesEliminarTuPropiaCuenta => ResourceManager.GetString("NoPuedesEliminarTuPropiaCuenta", resourceCulture)!;

        public static string NoPuedesDesactivarTuPropiaCuenta => ResourceManager.GetString("NoPuedesDesactivarTuPropiaCuenta", resourceCulture)!;

        public static string DebeHaberUnAdministrador => ResourceManager.GetString("DebeHaberUnAdministrador", resourceCulture)!;

        public static string SinCuentas => ResourceManager.GetString("SinCuentas", resourceCulture)!;

        public static string IniciarSesionTitulo => ResourceManager.GetString("IniciarSesionTitulo", resourceCulture)!;

        public static string ModulosPermitidos => ResourceManager.GetString("ModulosPermitidos", resourceCulture)!;

        public static string CuentaInactivaTexto => ResourceManager.GetString("CuentaInactivaTexto", resourceCulture)!;
    }
}
